### ISSUE TITLE
Errata: 3dFx to 3dfx

### ISSUE THREAD

**Issue by Chrissyx** [fabiensanglard/gebbwolf3#11]
https://github.com/fabiensanglard/gebbwolf3/blob/master/src/epilogue.tex#L25

`3dFx's Voodoo` has wrong capitalization, should be `3dfx's Voodoo`

**Comment by fabiensanglard** [comment]
Fixed in 1a93b5f039c02dab1c914d4c8852989e4ba8b468

**Comment by Chrissyx** [comment]
Was there any reason to revert this in cc7734c85ab323031e04f5767a2426da3085c10c?

**Comment by fabiensanglard** [comment]
I can't remember. I reverted the revert in 92f38b3082e3421114ad37f69f8783e606f29dc8. Thank you for taking the time to report the issue :) !
