### ISSUE TITLE
Missing Pages in v2.2

### ISSUE THREAD

**Issue by bilgincoskun** [fabiensanglard/gebbwolf3#20]
v2.2 is about 5 pages shorter than the previous versions due to missing pages in Team Chapter. The reason for that seems to be \end{document} before the missing text.

**Comment by fabiensanglard** [comment]
Can you be more explicit about which pages are missing? I looked at the history of `team.tex` and even in 2020 there was no `\end{document}` at the end.

**Comment by fabiensanglard** [comment]
You are correct :( ! I can see it now https://github.com/fabiensanglard/gebbwolf3/blob/master/src/team.tex#L586

**Comment by fabiensanglard** [comment]
Fixed in 74036d07229e0cc9dbf3a958eaf8b327c5266711

**Comment by fabiensanglard** [comment]
Thank you for taking the time to report this issue. I will update the PDF and upade the stores.
