### ISSUE TITLE
Errata: KB to kB

### ISSUE THREAD

**Issue by Chrissyx** [fabiensanglard/gebbwolf3#22]
https://github.com/fabiensanglard/gebbwolf3/blob/master/src/hardware.tex#L369

The IEC notation of kilobyte is kB with a lower case K.

**Comment by fabiensanglard** [comment]
Fixed in bf15bc7066e234809b26ba9507a8a755c9cac150. 

Thank you for your feedback!

**Comment by Chrissyx** [comment]
@fabiensanglard Did you change MB instead of KB to kB?

**Comment by fabiensanglard** [comment]
Oops. Reverted + fixed (hopefully) in 1b8b445af3e638ab126645c3d218cf8f626a896a.

Thanks for double checking.
