### ISSUE TITLE
make.sh fails identically on Ubuntu 22.04 and WSL2

### ISSUE THREAD

**Issue by BrendanL79** [fabiensanglard/gebbwolf3#23]
Installed all required packages and ran ./make.sh.

book.log shows:

`! Emergency stop.`
`<*> \def\forrelease{} \input{src/book.tex}`
`End of file on the terminal!`

[book_ubu2204.log](https://github.com/fabiensanglard/gebbwolf3/files/11161467/book_ubu2204.log)

EDIT: was able to resolve by adding an `\end{document}` line to src/team.tex

**Comment by fabiensanglard** [comment]
I am unable to repro locally. Tried on Mac and Linux. Are you using an older version of Latex?

**Comment by BrendanL79** [comment]
Hmm, not sure. On both WSL2 and my Ubu2204 VM I get:
```
$ latex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
```

**Comment by turric4n** [comment]
@BrendanL79 Look at this : https://github.com/fabiensanglard/gebbwolf3/issues/34
