### ISSUE TITLE
v2.2: p167 Aardwolf room is sealed

### ISSUE THREAD

**Issue by Leo-GAsss** [fabiensanglard/gebbwolf3#33]
> In the E2M8 drawing, notice there are no push walls leading to the red triangle; the room is sealed.

*is sealed* is a bit confusing. It seems that there is no way into the room.
However, the Aardwolf room does have a door (not a push wall though). Upon opening it, players will see the Aardwolf sign.

Source: https://wl6.fandom.com/wiki/Aardwolf_sign and https://joesiegler.blog/2016/08/call-apogee-and-say-aardwolf/
Video Demo: https://youtu.be/WPaMyyimbtc?si=wTRgQVoZSFfGjiAW&t=558

**Comment by fabiensanglard** [comment]
You are right. There is a detailed explanation by [Joe Siegler](https://joesiegler.blog/author/joesiegler/) [here](https://joesiegler.blog/2016/08/call-apogee-and-say-aardwolf/).

I should rework this section.
