### ISSUE TITLE
Careful when compiling using WSL2 

### ISSUE THREAD

**Issue by turric4n** [fabiensanglard/gebbwolf3#34]
Hi,

When cloning the repository using Windows and then using WSL2 to compile the book, you might encounter issues due to Carriage Return (CR) and Line Feed (LF) incompatibilities between the two operating systems. To avoid this, clone the repository using Git for Linux within the WSL2 distribution.

Feel free to update the README instructions to improve the compilation process for users on Windows/WSL.

**Comment by fabiensanglard** [comment]
Why not sent a PR?

**Comment by turric4n** [comment]
Ok Fabien, I'm doing it right now.

**Comment by fabiensanglard** [comment]
Thank you, you rock!
