### ISSUE TITLE
Compilation script does not check properly for Inkscape executable

### ISSUE THREAD

**Issue by deluxe** [fabiensanglard/gebbwolf3#8]
Compilation script `make.sh` does not check properly for Inkscape executable presence.

The check (`make.sh` lines 9-15) checks for `$INKSCAKE` which does not exist instead of `$INKSCAPE`
```bash
if [ ! -f $INKSCAKE ]; then
  echo "Inkscape executable is invalid"
  echo "Was expected at $INKSCAPE"
  exit 1
fi
```
but the condition is written with simple brackets `[ ]` which do not properly manage empty variables without double quotes, thus not detecting missing argument to `-f` test.

- **Steps to reproduce**
1. Do not install Inkscape, uninstall Inkscape, or change `INKSCAPE` variable value (`make.sh` line 4) to point to a non-existent path
2. Remove PNG already converted from SVG drawings to force conversion calls to Inkscape:
```bash
rm src/screenshots/386_layout_drawing.png src/screenshots/386_packaging_die.png src/screenshots/bsp_map.png src/screenshots/clear_screen_pixels.png src/screenshots/lines.png
rm src/screenshots_300dpi/386_layout_drawing.png src/screenshots_300dpi/386_packaging_die.png src/screenshots_300dpi/bsp_map.png src/screenshots_300dpi/clear_screen_pixels.png src/screenshots_300dpi/lines.png
```
3. Remove `2>&1` from Inkscape command lines (`make.sh` lines 52 and 60) to display errors
4. Launch the compilation with:
```bash
cd gebbwolf3/ && ./make.sh 
# or, see issue #7:
cd gebbwolf3/src/ && ../make.sh
```

- **Result**
The script does not stop at Inkscape check, continue and outputs an error message for each call to Inkscape:
```
Convert screenshots_svg/bsp_map.svg to PNG (100dpi).
../make.sh: line 53: /Applications/Inkscape.app/Contents/MacOS/inkscape: No such file or directory
[...]
```

- **Expected result**
The script should have stopped at Inkscape check and display:
```
Inkscape executable is invalid
Was expected at /Applications/Inkscape.app/Contents/MacOS/inkscape
```

**Comment by fabiensanglard** [comment]
Fix in f6556aa08b697bbad82e015df6efc1cfb85ba43b
